### ISSUE TITLE
Handle missing optional dependencies gracefully

### ISSUE THREAD

**Issue by idle-code** [idle-code/tempren#88]
When running `tempren` without optional dependency (`pymediainfo`) installed, following error is generated:
```console
❯ tempren -h Count
--- Logging error ---
Traceback (most recent call last):
  File "/home/idlecode/Projects/tempren/tempren/discovery.py", line 68, in visit_types_in_package
    module = importlib.import_module(name)
  File "/home/idlecode/.pyenv/versions/3.8.16/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/idlecode/Projects/tempren/tempren/tags/video.py", line 6, in <module>
    from pymediainfo import MediaInfo
ModuleNotFoundError: No module named 'pymediainfo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/idlecode/.pyenv/versions/3.8.16/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/home/idlecode/.pyenv/versions/3.8.16/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/home/idlecode/Projects/tempren/tempren/cli.py", line 43, in format
    return f"{record.levelname}: {record.getMessage()}"
  File "/home/idlecode/.pyenv/versions/3.8.16/lib/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/idlecode/Projects/tempren/.venv/bin/tempren", line 6, in <module>
    sys.exit(throwing_main())
  File "/home/idlecode/Projects/tempren/tempren/cli.py", line 673, in throwing_main
    sys.exit(main())
  File "/home/idlecode/Projects/tempren/tempren/cli.py", line 640, in main
    config = process_cli_configuration(argv)
  File "/home/idlecode/Projects/tempren/tempren/cli.py", line 515, in process_cli_configuration
    args = parser.parse_args(argv)
  File "/home/idlecode/.pyenv/versions/3.8.16/lib/python3.8/argparse.py", line 1768, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/idlecode/.pyenv/versions/3.8.16/lib/python3.8/argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/idlecode/.pyenv/versions/3.8.16/lib/python3.8/argparse.py", line 2006, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/home/idlecode/.pyenv/versions/3.8.16/lib/python3.8/argparse.py", line 1946, in consume_optional
    take_action(action, args, option_string)
  File "/home/idlecode/.pyenv/versions/3.8.16/lib/python3.8/argparse.py", line 1874, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/idlecode/Projects/tempren/tempren/cli.py", line 232, in __call__
    registry = build_tag_registry(
  File "/home/idlecode/Projects/tempren/tempren/pipeline.py", line 245, in build_tag_registry
    found_tags = discover_tags_in_package(tempren.tags)
  File "/home/idlecode/Projects/tempren/tempren/discovery.py", line 16, in discover_tags_in_package
    return _discover_classes_in_package(package, Tag)
  File "/home/idlecode/Projects/tempren/tempren/discovery.py", line 51, in _discover_classes_in_package
    visit_types_in_package(package, _visitor)
  File "/home/idlecode/Projects/tempren/tempren/discovery.py", line 73, in visit_types_in_package
    log.error(exc, f"Could not load module {name}")
Message: ModuleNotFoundError("No module named 'pymediainfo'")
Arguments: ('Could not load module tempren.tags.video',)
--- Logging error ---
Traceback (most recent call last):
  File "/home/idlecode/Projects/tempren/tempren/discovery.py", line 68, in visit_types_in_package
    module = importlib.import_module(name)
  File "/home/idlecode/.pyenv/versions/3.8.16/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/idlecode/Projects/tempren/tempren/tags/video.py", line 6, in <module>
    from pymediainfo import MediaInfo
ModuleNotFoundError: No module named 'pymediainfo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/idlecode/.pyenv/versions/3.8.16/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/home/idlecode/.pyenv/versions/3.8.16/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/home/idlecode/Projects/tempren/tempren/cli.py", line 43, in format
    return f"{record.levelname}: {record.getMessage()}"
  File "/home/idlecode/.pyenv/versions/3.8.16/lib/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/idlecode/Projects/tempren/.venv/bin/tempren", line 6, in <module>
    sys.exit(throwing_main())
  File "/home/idlecode/Projects/tempren/tempren/cli.py", line 673, in throwing_main
    sys.exit(main())
  File "/home/idlecode/Projects/tempren/tempren/cli.py", line 640, in main
    config = process_cli_configuration(argv)
  File "/home/idlecode/Projects/tempren/tempren/cli.py", line 515, in process_cli_configuration
    args = parser.parse_args(argv)
  File "/home/idlecode/.pyenv/versions/3.8.16/lib/python3.8/argparse.py", line 1768, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/idlecode/.pyenv/versions/3.8.16/lib/python3.8/argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/idlecode/.pyenv/versions/3.8.16/lib/python3.8/argparse.py", line 2006, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/home/idlecode/.pyenv/versions/3.8.16/lib/python3.8/argparse.py", line 1946, in consume_optional
    take_action(action, args, option_string)
  File "/home/idlecode/.pyenv/versions/3.8.16/lib/python3.8/argparse.py", line 1874, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/idlecode/Projects/tempren/tempren/cli.py", line 232, in __call__
    registry = build_tag_registry(
  File "/home/idlecode/Projects/tempren/tempren/pipeline.py", line 258, in build_tag_registry
    found_aliases = discover_aliases_in_package(tempren.tags)
  File "/home/idlecode/Projects/tempren/tempren/discovery.py", line 20, in discover_aliases_in_package
    return _discover_classes_in_package(package, TagAlias)
  File "/home/idlecode/Projects/tempren/tempren/discovery.py", line 51, in _discover_classes_in_package
    visit_types_in_package(package, _visitor)
  File "/home/idlecode/Projects/tempren/tempren/discovery.py", line 73, in visit_types_in_package
    log.error(exc, f"Could not load module {name}")
Message: ModuleNotFoundError("No module named 'pymediainfo'")
Arguments: ('Could not load module tempren.tags.video',)

  %Count(start: int = 0, step: int = 1, width: int = 0, common: bool = False)
         start - first element of generated sequence
         step - step added to previous element on each invocation
         width - number of characters taken by the number (will be zero-filled)
         common - use a single, global counter instead of per-directory ones
         If width is greater than zero, output will be a string value.

Generates sequential numbers for each invocation
```

**Comment by idle-code** [comment]
Fixed by catching `ModuleNotFoundError`
