### ISSUE TITLE
Fix dataclasses on Python 3.11

### ISSUE THREAD

**Issue by idle-code** [idle-code/tempren#91]
```
Traceback (most recent call last):
  File "/usr/local/bin/tempren", line 5, in <module>
    from tempren.cli import throwing_main
  File "/usr/local/lib/python3.11/site-packages/tempren/cli.py", line 20, in <module>
    from .pipeline import (
  File "/usr/local/lib/python3.11/site-packages/tempren/pipeline.py", line 8, in <module>
    from tempren.alias import AliasTagFactory, AliasTagFactoryFromClass
  File "/usr/local/lib/python3.11/site-packages/tempren/alias.py", line 5, in <module>
    from tempren.template.ast import Pattern
  File "/usr/local/lib/python3.11/site-packages/tempren/template/ast.py", line 17, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'tempren.primitives.Location'> for field location is not allowed: use default_factory
```

**Comment by idle-code** [comment]
Looks like it's no longer a problem
